spring.datasource.url: jdbc:h2:file:./camunda-h2-database

#
#CONFGIURAÇÃO ABAIXO É PARA BANCO DE DADOS SQL SERVE
#
#spring.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url: jdbc:sqlserver://NOTEL340;databaseName=CAMUNDANEW
#spring.datasource.username: sa
#spring.datasource.password: sa
#spring.jpa.hibernate.ddl-auto: validate
#spring.jpa.properties.hibernate.default_schema: dbo

#CONFIGURAÇÃO DA CREDENCIAL CAMUNDA
camunda.bpm.admin-user:
  id: demo
  password: demo
